### ISSUE TITLE
Question regarding the video formats

### ISSUE THREAD

**Issue by Kuronons** [D4n13l3k00/flipanimgen#1]
Hey !

I was wondering on the video formats that can be handled.
I see in your input sample that it takes in charge mp4.

Are there other video types that can be converted with your script ?

Thanks in advance for the enlightment !

O_oV

**Comment by D4n13l3k00** [comment]
Greetings! At the moment the code has a restriction on the file extension `.mp4`, but not on the file format. In theory, the script can accept any video that opencv can recognize. For tests, you can try adding `.mp4` to the full video name at the end.

Personally, I tested gifs by converting them to video using ffmpeg:

`ffmpeg -i input.gif output.mp4`

**Comment by Kuronons** [comment]
Thank for the explanation !
I just added link to your repo to my main's readme, tools section. (making my best to list all that is Flipper anims/graphic assets-related). So will add this info in description

Your tool is very interesting as it can handle videos while most convert gifs.

O_oV

**Comment by Kuronons** [comment]
Preview :
![image](https://github.com/user-attachments/assets/98188ddb-754d-47a4-a9b0-9cf5075e9f7f)

Hoping it will help people discover your tool and use it ! :)

**Comment by D4n13l3k00** [comment]
Thank you for your support and for adding the link to your repository! I truly appreciate it. If you have any feedback or suggestions for improvement, please feel free to let me know. Thank you once again!

**Comment by Kuronons** [comment]
Well I can see you know Ooggle's AM but I dunno if you re aware of all the existing tools/scripts for FZ anims. You may find inspiration on how to make yours improved by checking on what people made.
Probably not an exhaustive list but I gathered all I managed to find in the past 2 years there : 
https://github.com/Kuronons/FZ_graphics?tab=readme-ov-file#-links-of-interest--flipper-graphics---tools--apps

The one thing I can see by now would be the script to allow other extensions than mp4. Would require tests to check all that can be handled without issue. But I believe it would be some nice enhancement for users.

And YVW ! Just doing my lil part on sharing info on how to install / make / deal with FZ graphic assets. :metal:
